name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
  deployment-production:
    name: 'Production deployment'
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - run: echo "DEPLOYMENT"
  deployment-staging:
    name: 'Production staging'
    runs-on: ubuntu-latest
    environment: staging
    concurrency: staging
    steps:
      - run: echo "DEPLOYMENT"
